batch_size: 4
iters: 80000

train_dataset:
  type: Dataset
  dataset_root: ../rural
  train_path: ../rural/train.txt
  num_classes: 7
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ../rural
  val_path: ../rural/val.txt
  num_classes: 7
  transforms:
    - type: Normalize
  mode: val

model:
  type: SegFormer
  backbone:
    type: MixVisionTransformer_B1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/backbone/mix_vision_transformer_b1.tar.gz
  embedding_dim: 768
  num_classes: 7

optimizer:
    type: sgd

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  power: 0.9


loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]