_base_: '../_base_/cityscapes.yml'

batch_size: 4  # total: 4 GPUs
iters: 160000

optimizer:
  weight_decay: 5.0e-4

lr_scheduler:
  type: PolynomialDecay
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.005
  end_lr: 1.0e-6
  power: 0.9

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 150000   # 更适合 1024x512 分辨率
    - type: OhemCrossEntropyLoss
      min_kept: 150000
    - type: OhemCrossEntropyLoss
      min_kept: 150000
  coef: [ 1, 1, 1 ]

train_dataset:
  type: Dataset
  dataset_root: ../rural
  train_path: ../rural/train.txt
  num_classes: 7
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.125
      max_scale_factor: 1.5
      scale_step_size: 0.125
    - type: RandomPaddingCrop
      crop_size: [ 768, 768 ]
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomBlur
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ../rural
  val_path: ../rural/val.txt
  num_classes: 7
  transforms:
    - type: Normalize
  mode: val

model:
  type: PPLiteSeg
  num_classes: 7
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  arm_out_chs: [ 32, 64, 128 ]
  seg_head_inter_chs: [ 32, 64, 64 ]

test_config:
  aug_eval: True
  scales: [ 0.5, 1.0, 1.5 ]  # 多尺度测试，增强评估鲁棒性
